-- Q-Health Database Schema Migration
-- Generated for Supabase GitHub Sync and Realtime Queue Architecture

-- 1. Create clinics table
create table if not exists public.clinics (
    id text primary key,
    name text not null,
    location text not null,
    base_consult_time integer not null default 10,
    doctor_name text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create appointments (queue) table
create table if not exists public.appointments (
    id bigint generated by default as identity primary key,
    token_id integer not null,
    patient_name text not null,
    type text not null check (type in ('online', 'walk-in')),
    status text not null default 'waiting' check (status in ('waiting', 'in-progress', 'completed')),
    clinic_id text references public.clinics(id) on delete cascade default 'omr-health',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Indexes for performance
create index if not exists idx_appointments_token_id on public.appointments(token_id);
create index if not exists idx_appointments_status on public.appointments(status);
create index if not exists idx_appointments_clinic_id on public.appointments(clinic_id);

-- 3. Enable Row Level Security (RLS)
alter table public.clinics enable row level security;
alter table public.appointments enable row level security;

-- 4. RLS Policies for Publishable / Anon Key Access
-- Clinics Policies (Read-only for public, all for service_role)
create policy "Allow public read access on clinics"
    on public.clinics for select
    to anon, authenticated
    using (true);

create policy "Allow public insert on clinics"
    on public.clinics for insert
    to anon, authenticated
    with check (true);

create policy "Allow public update on clinics"
    on public.clinics for update
    to anon, authenticated
    using (true);

-- Appointments Policies (Public can read, book tokens, and update queue status)
create policy "Allow public read access on appointments"
    on public.appointments for select
    to anon, authenticated
    using (true);

create policy "Allow public insert on appointments"
    on public.appointments for insert
    to anon, authenticated
    with check (true);

create policy "Allow public update on appointments"
    on public.appointments for update
    to anon, authenticated
    using (true);

create policy "Allow public delete on appointments"
    on public.appointments for delete
    to anon, authenticated
    using (true);

-- 5. Enable Supabase Realtime for table updates
-- Replica identity full ensures old record values are broadcasted on UPDATE and DELETE
alter table public.appointments replica identity full;
alter table public.clinics replica identity full;

-- Add tables to the supabase_realtime publication
do $$
begin
    if not exists (
        select 1 from pg_publication_tables 
        where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'appointments'
    ) then
        alter publication supabase_realtime add table public.appointments;
    end if;

    if not exists (
        select 1 from pg_publication_tables 
        where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'clinics'
    ) then
        alter publication supabase_realtime add table public.clinics;
    end if;
end $$;
